# Javascript Node CircleCI configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:11.0.2-jdk-node

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn
      - run: yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run mocha
      - run:
          name: test
          command: yarn test --reporter mocha-junit-reporter --reporter-option mochaFile=./test-results/mocha/test-results.xml
          when: always

      # Run eslint
      - run:
          name: eslint
          command: yarn lint --format junit --output-file ./test-results/eslint/eslint.xml
          when: always

      # Upload results
      - store_test_results:
          path: ./test-results

      - store_artifacts: # upload test coverage as artifact
          path: ./test-coverage

      - run: bash <(curl -s https://codecov.io/bash)

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy-latest:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Authenticate with npm registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" >> ~/repo/.npmrc

      - run:
          name: Publish a public package with the tag "latest"
          command: npm publish --public --tag latest

workflows:
  version: 2.1
  test-publish:
    jobs:
      - test
      - deploy-latest:
          requires:
            - test
          filters:
            branches:
              ignore:
                /.*/
            tags:
              only:
                /^tag-test-v2.*/
